---
- hosts: localhost
  tasks:

    #
    # System configuration
    #

  - name: Change locale
    locale_gen: name=en_GB.UTF-8 state=present

  - name: Set keyboard layout
    shell: setxkbmap gb

  - name: Uninstall Nano
    apt: name=nano state=absent

  - name: Directory for the host-guest communication
    file: path=/home/vagrant/Desktop/tankwar_host state=directory

    #
    # VIM Configuration
    #

  - name: Install VIM
    apt: name=vim state=present

  - name: Create VIM config directories
    file: path=~/.vim/{{ item }} state=directory
    with_items:
      - ftdetect
      - indent
      - syntax

  - name: Apply VIM configuration for Scala
    get_url: url="https://raw.githubusercontent.com/derekwyatt/vim-scala/master/syntax/scala.vim"
        dest=~/.vim/{{ item }}
        mode=0644
    with_items:
      - ftdetect
      - indent
      - syntax

    #
    # Sublime Text configuration
    #

  - name: Add Subilme Text Repository
    apt_repository: repo="ppa:webupd8team/sublime-text-3"
        validate_certs=no
        state=present

  - name: Install Sublime Text
    apt: name=sublime-text-installer state=present

  - name: Make Sublime Text the default editor
    lineinfile: dest=/etc/gnome/defaults.list
        state=present
        regexp='gedit.desktop'
        line='sublime-text-3.desktop'
        backup=yes

    #
    # JDK 8
    #

  - name: Add JDK 8 Repository
    apt_repository: repo="ppa:openjdk-r/ppa" validate_certs=no state=present

  - name: Install JDK 8
    apt: name=openjdk-8-jdk state=latest

    #
    # Scala and SBT
    #

  - name: Install Scala
    apt: name=scala state=latest

  - name: Add SBT Repository
    apt_repository: repo="deb https://dl.bintray.com/sbt/debian /"
        validate_certs=no
        state=present

  - name: Install SBT
    apt: name=sbt force=yes state=latest

  - name: Install GIT
    apt: name=git state=present

  #
  # Tankwar Repository
  #

  - name: Clone TankWar Repository
    git: repo=https://github.com/ColOfAbRiX/tankwar.git
        dest=~/Desktop/tankwar_github
