---
- hosts: localhost
  tasks:

    #
    # System configuration
    #

  - name: Change locale
    locale_gen: name=en_GB.UTF-8 state=present

  - name: Uninstall Nano
    apt: name=nano state=absent

  - name: Directory for the host-guest communication
    file: path=/home/vagrant/Desktop/tankwar_host state=directory

    #
    # VIM Configuration
    #

  - name: Install VIM
    apt: name=vim state=present

  - name: Create VIM config directories
    file: path=~/.vim/{{ item }} state=directory
    with_items:
      - ftdetect
      - indent
      - syntax

  - name: Apply VIM configuration for Scala
    get_url: dest=~/.vim/{{ item }} mode=0644 url="https://raw.githubusercontent.com/derekwyatt/vim-scala/master/syntax/scala.vim"
    with_items:
      - ftdetect
      - indent
      - syntax

    #
    # Atom configuration
    #

  - name: Download Atom package
    get_url: url="https://github.com/atom/atom/releases/download/v1.4.1/atom-amd64.deb" dest=/tmp/atom-1.4.1.deb

  - name: Install Atom
    apt: deb=/tmp/atom-1.4.1.deb

    #
    # JDK 8
    #

  - name: Add JDK 8 Repository
    apt_repository: repo="ppa:openjdk-r/ppa" validate_certs=no state=present

  - name: Install JDK 8
    apt: name=openjdk-8-jdk state=latest

    #
    # Scala and SBT
    #

  - name: Install Scala
    apt: name=scala state=latest

  - name: Add SBT Repository
    apt_repository: repo="deb https://dl.bintray.com/sbt/debian /" validate_certs=no state=present

  - name: Install SBT
    apt: name=sbt force=yes state=latest

  - name: Install GIT
    apt: name=git state=present

  #
  # Tankwar Repository
  #

  - name: Clone TankWar Repository
    git: repo=https://github.com/ColOfAbRiX/tankwar.git dest=~/Desktop/tankwar_github