# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.network "private_network", ip: "192.168.33.128"

  config.vm.network "public_network"

  config.ssh.insert_key = false

  config.vm.synced_folder "../../", "/home/vagrant/Desktop/tankwar_host"

  config.vm.boot_timeout = 300

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "TankWar-Dev"
    vb.memory = "2048"
    vb.cpus = 2
    vb.customize [
      "modifyvm", :id,
      "--cpuexecutioncap", "90",
      "--accelerate3d", "on",
      "--vram", "64",
      "--draganddrop", "bidirectional",
      "--clipboard", "bidirectional",
      "--usb", "on",
      "--usbehci", "on",
      "--nic3", "intnet",
      "--intnet3", "internal"
    ]
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install --reinstall ca-certificates
    sudo -E apt-add-repository -y ppa:ansible/ansible
    sudo apt-get update -qq
    sudo apt-get install -qy software-properties-common ansible
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible-vagrant.yml"
  end

end